language: java
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
addons:
  apt:
    update: true
install: true
notifications:
  email:
    - xmlunit-commits@lists.sourceforge.net
after_success:
  - mvn clean test jacoco:report coveralls:report -Pjacoco
