language: java
matrix:
  include:
    - dist: trusty
      jdk: openjdk7
    - dist: trusty
      jdk: openjdk8
    - dist: xenial
      jdk: openjdk10
    - dist: xenial
      jdk: openjdk11
    - dist: trusty
      jdk: oraclejdk8
    - dist: trusty
      jdk: oraclejdk9
    - dist: trusty
      jdk: oraclejdk11
    - dist: bionic
      jdk: openjdk14
addons:
  apt:
    update: true
install: true
script:
  - mvn install -B
  - cd compat-tests && ./hamcrest-test.sh 2.6.5-SNAPSHOT 2.2
notifications:
  email:
    - xmlunit-commits@lists.sourceforge.net
after_success:
  - mvn clean test jacoco:report coveralls:report -Pjacoco
